# Generated by Django 5.1.2 on 2024-11-03 18:01

from django.db import migrations
from django.conf import settings

import os, csv


def import_csv_towns(apps, schema_editor):
    Town = apps.get_model("town", "Town")

    with open(os.path.join(settings.BASE_DIR, 'town', 'migrations', 'spain_towns.csv')) as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            Town.objects.create(
                zip_code = row['codigo_postal'],
                name = row['municipio_nombre']
            )

class Migration(migrations.Migration):

    dependencies = [
        ('town', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_csv_towns)
    ]
