# Generated by Django 5.1.2 on 2024-11-05 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('town', '0002_add_towns_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('observations', models.CharField(max_length=2048, null=True)),
                ('street', models.CharField(max_length=512)),
                ('number', models.CharField(default='s/n', max_length=512)),
                ('floor', models.CharField(max_length=512, null=True)),
                ('latitude', models.FloatField(max_length=32, null=True)),
                ('longitude', models.FloatField(max_length=32, null=True)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='town.town')),
            ],
        ),
    ]
